<a href="https://colab.research.google.com/github/MicaelaMarques/Eco_project/blob/consumer_branch/C%C3%B3pia_de_Customer_segment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import plotly.express as px

In [ ]:
import pandas as pd

customer_behavior = pd.read_csv('/content/Amazon Customer Behavior Survey.csv')

In [ ]:
display(customer_behavior)
customer_behavior.describe()

,Timestamp,age,Gender,Purchase_Frequency,Purchase_Categories,Personalized_Recommendation_Frequency,Browsing_Frequency,Product_Search_Method,Search_Result_Exploration,Customer_Reviews_Importance,...,Saveforlater_Frequency,Review_Left,Review_Reliability,Review_Helpfulness,Personalized_Recommendation_Frequency,Recommendation_Helpfulness,Rating_Accuracy,Shopping_Satisfaction,Service_Appreciation,Improvement_Areas
0,2023/06/04 1:28:19 PM GMT+5:30,23,Female,Few times a month,Beauty and Personal Care,Yes,Few times a week,Keyword,Multiple pages,1,...,Sometimes,Yes,Occasionally,Yes,2,Yes,1,1,Competitive prices,Reducing packaging waste
1,2023/06/04 2:30:44 PM GMT+5:30,23,Female,Once a month,Clothing and Fashion,Yes,Few times a month,Keyword,Multiple pages,1,...,Rarely,No,Heavily,Yes,2,Sometimes,3,2,Wide product selection,Reducing packaging waste
2,2023/06/04 5:04:56 PM GMT+5:30,24,Prefer not to say,Few times a month,Groceries and Gourmet Food;Clothing and Fashion,No,Few times a month,Keyword,Multiple pages,2,...,Rarely,No,Occasionally,No,4,No,3,3,Competitive prices,Product quality and accuracy
3,2023/06/04 5:13:00 PM GMT+5:30,24,Female,Once a month,Beauty and Personal Care;Clothing and Fashion;...,Sometimes,Few times a month,Keyword,First page,5,...,Sometimes,Yes,Heavily,Yes,3,Sometimes,3,4,Competitive prices,Product quality and accuracy
4,2023/06/04 5:28:06 PM GMT+5:30,22,Female,Less than once a month,Beauty and Personal Care;Clothing and Fashion,Yes,Few times a month,Filter,Multiple pages,1,...,Rarely,No,Heavily,Yes,4,Yes,2,2,Competitive prices,Product quality and accuracy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
597,2023/06/12 4:02:02 PM GMT+5:30,23,Female,Once a week,Beauty and Personal Care,Sometimes,Few times a week,categories,Multiple pages,4,...,Sometimes,Yes,Moderately,Sometimes,3,Sometimes,3,4,Competitive prices,Customer service responsiveness
598,2023/06/12 4:02:53 PM GMT+5:30,23,Female,Once a week,Clothing and Fashion,Sometimes,Few times a week,Filter,Multiple pages,3,...,Sometimes,Yes,Heavily,Sometimes,3,Sometimes,3,3,Product recommendations,Reducing packaging waste
599,2023/06/12 4:03:59 PM GMT+5:30,23,Female,Once a month,Beauty and Personal Care,Sometimes,Few times a week,categories,Multiple pages,3,...,Sometimes,Yes,Occasionally,Sometimes,3,Sometimes,2,3,Wide product selection,Product quality and accuracy
600,2023/06/12 9:57:20 PM GMT+5:30,23,Female,Few times a month,Beauty and Personal Care;Clothing and Fashion;...,Yes,Few times a month,Keyword,Multiple pages,1,...,Sometimes,No,Heavily,Yes,2,Yes,2,2,Wide product selection,Product quality and accuracy
601,2023/06/16 9:16:05 AM GMT+5:30,23,Female,Once a week,Clothing and Fashion,Sometimes,Multiple times a day,Keyword,Multiple pages,3,...,Sometimes,Yes,Moderately,Sometimes,3,Sometimes,3,3,Product recommendations,Product quality and accuracy

,age,Customer_Reviews_Importance,Personalized_Recommendation_Frequency,Rating_Accuracy,Shopping_Satisfaction
count,602.000000,602.000000,602.000000,602.000000,602.000000
mean,30.790698,2.480066,2.699336,2.672757,2.463455
std,10.193276,1.185226,1.042028,0.899744,1.012152
min,3.000000,1.000000,1.000000,1.000000,1.000000
25%,23.000000,1.000000,2.000000,2.000000,2.000000
50%,26.000000,3.000000,3.000000,3.000000,2.000000
75%,36.000000,3.000000,3.000000,3.000000,3.000000
max,67.000000,5.000000,5.000000,5.000000,5.000000

In [ ]:
customer_behavior.describe

<bound method NDFrame.describe of                           Timestamp  age             Gender  \
0    2023/06/04 1:28:19 PM GMT+5:30   23             Female
1    2023/06/04 2:30:44 PM GMT+5:30   23             Female
2    2023/06/04 5:04:56 PM GMT+5:30   24  Prefer not to say
3    2023/06/04 5:13:00 PM GMT+5:30   24             Female
4    2023/06/04 5:28:06 PM GMT+5:30   22             Female
..                              ...  ...                ...
597  2023/06/12 4:02:02 PM GMT+5:30   23             Female
598  2023/06/12 4:02:53 PM GMT+5:30   23             Female
599  2023/06/12 4:03:59 PM GMT+5:30   23             Female
600  2023/06/12 9:57:20 PM GMT+5:30   23             Female
601  2023/06/16 9:16:05 AM GMT+5:30   23             Female

         Purchase_Frequency  \
0         Few times a month
1              Once a month
2         Few times a month
3              Once a month
4    Less than once a month
..                      ...
597             Once a week
598             Once a week
599            Once a month
600       Few times a month
601             Once a week

                                   Purchase_Categories  \
0                             Beauty and Personal Care
1                                 Clothing and Fashion
2      Groceries and Gourmet Food;Clothing and Fashion
3    Beauty and Personal Care;Clothing and Fashion;...
4        Beauty and Personal Care;Clothing and Fashion
..                                                 ...
597                           Beauty and Personal Care
598                               Clothing and Fashion
599                           Beauty and Personal Care
600  Beauty and Personal Care;Clothing and Fashion;...
601                               Clothing and Fashion

    Personalized_Recommendation_Frequency    Browsing_Frequency  \
0                                     Yes      Few times a week
1                                     Yes     Few times a month
2                                      No     Few times a month
3                               Sometimes     Few times a month
4                                     Yes     Few times a month
..                                    ...                   ...
597                             Sometimes      Few times a week
598                             Sometimes      Few times a week
599                             Sometimes      Few times a week
600                                   Yes     Few times a month
601                             Sometimes  Multiple times a day

    Product_Search_Method Search_Result_Exploration  \
0                 Keyword            Multiple pages
1                 Keyword            Multiple pages
2                 Keyword            Multiple pages
3                 Keyword                First page
4                  Filter            Multiple pages
..                    ...                       ...
597            categories            Multiple pages
598                Filter            Multiple pages
599            categories            Multiple pages
600               Keyword            Multiple pages
601               Keyword            Multiple pages

     Customer_Reviews_Importance  ... Saveforlater_Frequency Review_Left  \
0                              1  ...              Sometimes         Yes
1                              1  ...                 Rarely          No
2                              2  ...                 Rarely          No
3                              5  ...              Sometimes         Yes
4                              1  ...                 Rarely          No
..                           ...  ...                    ...         ...
597                            4  ...              Sometimes         Yes
598                            3  ...              Sometimes         Yes
599                            3  ...              Sometimes         Yes
600                            1  ...              Sometimes          No
601                            3  ...              Sometimes         Yes

    Review_Reliability Review_Helpfulness  \
0         Occasionally                Yes
1              Heavily                Yes
2         Occasionally                 No
3              Heavily                Yes
4              Heavily                Yes
..                 ...                ...
597         Moderately          Sometimes
598            Heavily          Sometimes
599       Occasionally          Sometimes
600            Heavily                Yes
601         Moderately          Sometimes

    Personalized_Recommendation_Frequency  Recommendation_Helpfulness  \
0                                        2                        Yes
1                                        2                  Sometimes
2                                        4                         No
3                                        3                  Sometimes
4                                        4                        Yes
..                                     ...                        ...
597                                      3                  Sometimes
598                                      3                  Sometimes
599                                      3                  Sometimes
600                                      2                        Yes
601                                      3                  Sometimes

    Rating_Accuracy   Shopping_Satisfaction     Service_Appreciation  \
0                  1                      1       Competitive prices
1                  3                      2   Wide product selection
2                  3                      3       Competitive prices
3                  3                      4       Competitive prices
4                  2                      2       Competitive prices
..               ...                    ...                      ...
597                3                      4       Competitive prices
598                3                      3  Product recommendations
599                2                      3   Wide product selection
600                2                      2   Wide product selection
601                3                      3  Product recommendations

                   Improvement_Areas
0           Reducing packaging waste
1           Reducing packaging waste
2       Product quality and accuracy
3       Product quality and accuracy
4       Product quality and accuracy
..                               ...
597  Customer service responsiveness
598         Reducing packaging waste
599     Product quality and accuracy
600     Product quality and accuracy
601     Product quality and accuracy

[602 rows x 23 columns]>

In [ ]:
import uuid

# Generate a UUID for each customer
customer_behavior['customer_id'] = [str(uuid.uuid4()) for _ in range(len(customer_behavior))]

In [ ]:
customer_behavior.dtypes

Timestamp                                 object
age                                        int64
Gender                                    object
Purchase_Frequency                        object
Purchase_Categories                       object
Personalized_Recommendation_Frequency     object
Browsing_Frequency                        object
Product_Search_Method                     object
Search_Result_Exploration                 object
Customer_Reviews_Importance                int64
Add_to_Cart_Browsing                      object
Cart_Completion_Frequency                 object
Cart_Abandonment_Factors                  object
Saveforlater_Frequency                    object
Review_Left                               object
Review_Reliability                        object
Review_Helpfulness                        object
Personalized_Recommendation_Frequency      int64
Recommendation_Helpfulness                object
Rating_Accuracy                            int64
Shopping_Satisfaction                      int64
Service_Appreciation                      object
Improvement_Areas                         object
customer_id                               object
dtype: object

In [ ]:
customer_behavior['Purchase_Categories'].unique()

array(['Beauty and Personal Care', 'Clothing and Fashion',
       'Groceries and Gourmet Food;Clothing and Fashion',
       'Beauty and Personal Care;Clothing and Fashion;others',
       'Beauty and Personal Care;Clothing and Fashion',
       'Beauty and Personal Care;Clothing and Fashion;Home and Kitchen',
       'Clothing and Fashion;Home and Kitchen', 'others',
       'Clothing and Fashion;others',
       'Beauty and Personal Care;Home and Kitchen',
       'Groceries and Gourmet Food',
       'Groceries and Gourmet Food;Clothing and Fashion;others',
       'Groceries and Gourmet Food;Beauty and Personal Care;Clothing and Fashion;Home and Kitchen',
       'Groceries and Gourmet Food;Beauty and Personal Care;Clothing and Fashion;Home and Kitchen;others',
       'Home and Kitchen', 'Beauty and Personal Care;others',
       'Beauty and Personal Care;Home and Kitchen;others',
       'Home and Kitchen;others',
       'Groceries and Gourmet Food;Home and Kitchen',
       'Beauty and Personal Care;Clothing and Fashion;Home and Kitchen;others',
       'Groceries and Gourmet Food;Beauty and Personal Care;Home and Kitchen',
       'Groceries and Gourmet Food;Home and Kitchen;others',
       'Groceries and Gourmet Food;Clothing and Fashion;Home and Kitchen;others',
       'Groceries and Gourmet Food;Beauty and Personal Care',
       'Clothing and Fashion;Home and Kitchen;others',
       'Groceries and Gourmet Food;Beauty and Personal Care;Clothing and Fashion',
       'Groceries and Gourmet Food;Clothing and Fashion;Home and Kitchen',
       'Groceries and Gourmet Food;Beauty and Personal Care;others',
       'Groceries and Gourmet Food;Beauty and Personal Care;Clothing and Fashion;others'],
      dtype=object)

In [ ]:
customer_behavior['category_split'] = customer_behavior['Purchase_Categories'].str.split(';')

# Flatten the lists and find unique values
unique_categories = set([category for sublist in customer_behavior['category_split'].dropna() for category in sublist])

print(unique_categories)

{'Home and Kitchen', 'Groceries and Gourmet Food', 'Beauty and Personal Care', 'Clothing and Fashion', 'others'}

In [ ]:
customer_behavior['category_split']

0                             [Beauty and Personal Care]
1                                 [Clothing and Fashion]
2      [Groceries and Gourmet Food, Clothing and Fash...
3      [Beauty and Personal Care, Clothing and Fashio...
4       [Beauty and Personal Care, Clothing and Fashion]
                             ...
597                           [Beauty and Personal Care]
598                               [Clothing and Fashion]
599                           [Beauty and Personal Care]
600    [Beauty and Personal Care, Clothing and Fashio...
601                               [Clothing and Fashion]
Name: category_split, Length: 602, dtype: object

In [ ]:
customer_behavior_categorized = customer_behavior.copy()

In [ ]:
#Category split

df_exploded = customer_behavior_categorized.explode('category_split')

df_exploded = df_exploded.rename(columns={'purchase_category_split': 'individual_category'})

display(df_exploded)

,Timestamp,age,Gender,Purchase_Frequency,Purchase_Categories,Personalized_Recommendation_Frequency,Browsing_Frequency,Product_Search_Method,Search_Result_Exploration,Customer_Reviews_Importance,...,Review_Reliability,Review_Helpfulness,Personalized_Recommendation_Frequency,Recommendation_Helpfulness,Rating_Accuracy,Shopping_Satisfaction,Service_Appreciation,Improvement_Areas,customer_id,category_split
0,2023/06/04 1:28:19 PM GMT+5:30,23,Female,Few times a month,Beauty and Personal Care,Yes,Few times a week,Keyword,Multiple pages,1,...,Occasionally,Yes,2,Yes,1,1,Competitive prices,Reducing packaging waste,efe6a20e-278d-4256-9011-9c7c36785bde,Beauty and Personal Care
1,2023/06/04 2:30:44 PM GMT+5:30,23,Female,Once a month,Clothing and Fashion,Yes,Few times a month,Keyword,Multiple pages,1,...,Heavily,Yes,2,Sometimes,3,2,Wide product selection,Reducing packaging waste,d6c5723a-6a01-4d35-99c4-08de25969e34,Clothing and Fashion
2,2023/06/04 5:04:56 PM GMT+5:30,24,Prefer not to say,Few times a month,Groceries and Gourmet Food;Clothing and Fashion,No,Few times a month,Keyword,Multiple pages,2,...,Occasionally,No,4,No,3,3,Competitive prices,Product quality and accuracy,e876aa4a-c80a-4ea8-a473-8a40d294a056,Groceries and Gourmet Food
2,2023/06/04 5:04:56 PM GMT+5:30,24,Prefer not to say,Few times a month,Groceries and Gourmet Food;Clothing and Fashion,No,Few times a month,Keyword,Multiple pages,2,...,Occasionally,No,4,No,3,3,Competitive prices,Product quality and accuracy,e876aa4a-c80a-4ea8-a473-8a40d294a056,Clothing and Fashion
3,2023/06/04 5:13:00 PM GMT+5:30,24,Female,Once a month,Beauty and Personal Care;Clothing and Fashion;...,Sometimes,Few times a month,Keyword,First page,5,...,Heavily,Yes,3,Sometimes,3,4,Competitive prices,Product quality and accuracy,1d93ee7d-2c8b-45f6-80ae-dc364ffe157c,Beauty and Personal Care
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599,2023/06/12 4:03:59 PM GMT+5:30,23,Female,Once a month,Beauty and Personal Care,Sometimes,Few times a week,categories,Multiple pages,3,...,Occasionally,Sometimes,3,Sometimes,2,3,Wide product selection,Product quality and accuracy,da66537e-1375-4b0a-87d4-d6f67ead3cc0,Beauty and Personal Care
600,2023/06/12 9:57:20 PM GMT+5:30,23,Female,Few times a month,Beauty and Personal Care;Clothing and Fashion;...,Yes,Few times a month,Keyword,Multiple pages,1,...,Heavily,Yes,2,Yes,2,2,Wide product selection,Product quality and accuracy,9f1a38a2-0b81-44cc-b715-de43cb83e079,Beauty and Personal Care
600,2023/06/12 9:57:20 PM GMT+5:30,23,Female,Few times a month,Beauty and Personal Care;Clothing and Fashion;...,Yes,Few times a month,Keyword,Multiple pages,1,...,Heavily,Yes,2,Yes,2,2,Wide product selection,Product quality and accuracy,9f1a38a2-0b81-44cc-b715-de43cb83e079,Clothing and Fashion
600,2023/06/12 9:57:20 PM GMT+5:30,23,Female,Few times a month,Beauty and Personal Care;Clothing and Fashion;...,Yes,Few times a month,Keyword,Multiple pages,1,...,Heavily,Yes,2,Yes,2,2,Wide product selection,Product quality and accuracy,9f1a38a2-0b81-44cc-b715-de43cb83e079,others
601,2023/06/16 9:16:05 AM GMT+5:30,23,Female,Once a week,Clothing and Fashion,Sometimes,Multiple times a day,Keyword,Multiple pages,3,...,Moderately,Sometimes,3,Sometimes,3,3,Product recommendations,Product quality and accuracy,570cf100-8825-4bde-84e1-9ba450eb7236,Clothing and Fashion

In [ ]:
#age grouped

bins = [10, 20, 30, 40, 50, 60, 70]
labels = ['10-19', '20-29', '30-39', '40-49', '50-59', '60-69']

df_exploded['age_group'] = pd.cut(df_exploded['age'], bins=bins, labels=labels, right=False)
df_exploded

df_exploded.groupby(['category_split', 'age_group'])['customer_id'].nunique()

<ipython-input-17-dad6d5350d9c>:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_exploded.groupby(['category_split', 'age_group'])['customer_id'].nunique()

category_split              age_group
Beauty and Personal Care    10-19         11
                            20-29        174
                            30-39         72
                            40-49         44
                            50-59         13
                            60-69          4
Clothing and Fashion        10-19         21
                            20-29        177
                            30-39         84
                            40-49         45
                            50-59         15
                            60-69          1
Groceries and Gourmet Food  10-19          4
                            20-29         39
                            30-39         37
                            40-49         20
                            50-59          9
                            60-69          2
Home and Kitchen            10-19          5
                            20-29         95
                            30-39         68
                            40-49         34
                            50-59         14
                            60-69          3
others                      10-19          7
                            20-29         84
                            30-39         44
                            40-49         21
                            50-59          8
                            60-69          2
Name: customer_id, dtype: int64

In [ ]:
#improvement areas grouped

data = df_exploded['Improvement_Areas']
def categorize_area(area):
    target_groups = [
        'Customer service responsiveness',
        'Product quality and accuracy',
        'Reducing packaging waste',
        'Shipping speed and reliability'
    ]
    if area in target_groups:
        return area
    else:
        return 'Others'
df_exploded['Improvement_Areas_New'] = df_exploded['Improvement_Areas'].apply(categorize_area)
df_exploded

,Timestamp,age,Gender,Purchase_Frequency,Purchase_Categories,Personalized_Recommendation_Frequency,Browsing_Frequency,Product_Search_Method,Search_Result_Exploration,Customer_Reviews_Importance,...,Personalized_Recommendation_Frequency,Recommendation_Helpfulness,Rating_Accuracy,Shopping_Satisfaction,Service_Appreciation,Improvement_Areas,customer_id,category_split,age_group,Improvement_Areas_New
0,2023/06/04 1:28:19 PM GMT+5:30,23,Female,Few times a month,Beauty and Personal Care,Yes,Few times a week,Keyword,Multiple pages,1,...,2,Yes,1,1,Competitive prices,Reducing packaging waste,efe6a20e-278d-4256-9011-9c7c36785bde,Beauty and Personal Care,20-29,Reducing packaging waste
1,2023/06/04 2:30:44 PM GMT+5:30,23,Female,Once a month,Clothing and Fashion,Yes,Few times a month,Keyword,Multiple pages,1,...,2,Sometimes,3,2,Wide product selection,Reducing packaging waste,d6c5723a-6a01-4d35-99c4-08de25969e34,Clothing and Fashion,20-29,Reducing packaging waste
2,2023/06/04 5:04:56 PM GMT+5:30,24,Prefer not to say,Few times a month,Groceries and Gourmet Food;Clothing and Fashion,No,Few times a month,Keyword,Multiple pages,2,...,4,No,3,3,Competitive prices,Product quality and accuracy,e876aa4a-c80a-4ea8-a473-8a40d294a056,Groceries and Gourmet Food,20-29,Product quality and accuracy
2,2023/06/04 5:04:56 PM GMT+5:30,24,Prefer not to say,Few times a month,Groceries and Gourmet Food;Clothing and Fashion,No,Few times a month,Keyword,Multiple pages,2,...,4,No,3,3,Competitive prices,Product quality and accuracy,e876aa4a-c80a-4ea8-a473-8a40d294a056,Clothing and Fashion,20-29,Product quality and accuracy
3,2023/06/04 5:13:00 PM GMT+5:30,24,Female,Once a month,Beauty and Personal Care;Clothing and Fashion;...,Sometimes,Few times a month,Keyword,First page,5,...,3,Sometimes,3,4,Competitive prices,Product quality and accuracy,1d93ee7d-2c8b-45f6-80ae-dc364ffe157c,Beauty and Personal Care,20-29,Product quality and accuracy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599,2023/06/12 4:03:59 PM GMT+5:30,23,Female,Once a month,Beauty and Personal Care,Sometimes,Few times a week,categories,Multiple pages,3,...,3,Sometimes,2,3,Wide product selection,Product quality and accuracy,da66537e-1375-4b0a-87d4-d6f67ead3cc0,Beauty and Personal Care,20-29,Product quality and accuracy
600,2023/06/12 9:57:20 PM GMT+5:30,23,Female,Few times a month,Beauty and Personal Care;Clothing and Fashion;...,Yes,Few times a month,Keyword,Multiple pages,1,...,2,Yes,2,2,Wide product selection,Product quality and accuracy,9f1a38a2-0b81-44cc-b715-de43cb83e079,Beauty and Personal Care,20-29,Product quality and accuracy
600,2023/06/12 9:57:20 PM GMT+5:30,23,Female,Few times a month,Beauty and Personal Care;Clothing and Fashion;...,Yes,Few times a month,Keyword,Multiple pages,1,...,2,Yes,2,2,Wide product selection,Product quality and accuracy,9f1a38a2-0b81-44cc-b715-de43cb83e079,Clothing and Fashion,20-29,Product quality and accuracy
600,2023/06/12 9:57:20 PM GMT+5:30,23,Female,Few times a month,Beauty and Personal Care;Clothing and Fashion;...,Yes,Few times a month,Keyword,Multiple pages,1,...,2,Yes,2,2,Wide product selection,Product quality and accuracy,9f1a38a2-0b81-44cc-b715-de43cb83e079,others,20-29,Product quality and accuracy
601,2023/06/16 9:16:05 AM GMT+5:30,23,Female,Once a week,Clothing and Fashion,Sometimes,Multiple times a day,Keyword,Multiple pages,3,...,3,Sometimes,3,3,Product recommendations,Product quality and accuracy,570cf100-8825-4bde-84e1-9ba450eb7236,Clothing and Fashion,20-29,Product quality and accuracy

In [ ]:
#Product search method analysis by product category

cb_search_result_grouped = df_exploded.groupby(['category_split', 'Product_Search_Method']).agg({'customer_id':'nunique'})
display(cb_search_result_grouped)

fig = px.histogram (df_exploded, x='Product_Search_Method', histfunc="sum", nbins=8, text_auto=True)
fig.show()

fig2 = px.histogram(df_exploded, x = ('category_split'), barmode = 'group', color = 'Product_Search_Method', text_auto=True)
fig2.show()

fig3 = px.histogram(df_exploded, x = ('age_group'), barmode = 'group', color = 'Product_Search_Method', text_auto=True)
fig3.show()

                                                  customer_id
category_split             Product_Search_Method
Beauty and Personal Care   Filter                          68
                           Keyword                        112
                           categories                     125
                           others                          12
Clothing and Fashion       Filter                          71
                           Keyword                        134
                           categories                     121
                           others                          15
Groceries and Gourmet Food Filter                          23
                           Keyword                         51
                           categories                      33
                           others                           4
Home and Kitchen           Filter                          51
                           Keyword                         92
                           categories                      65
                           others                          11
others                     Filter                          18
                           Keyword                         90
                           categories                      36
                           others                          21

In [ ]:
#Search_Result_Exploration analysis by product category

cb_product_search_grouped = df_exploded.groupby(['category_split', 'Search_Result_Exploration']).agg({'customer_id':'nunique'})
display(cb_product_search_grouped)

fig4 = px.histogram (df_exploded, x='Search_Result_Exploration', histfunc="sum", nbins=8, text_auto=True)
fig4.show()

fig5 = px.histogram(df_exploded, x = ('category_split'), histfunc="sum", barmode = 'group', color = 'Search_Result_Exploration', text_auto=True)
fig5.show()

fig6 = px.histogram(df_exploded, x = ('Gender'), histfunc="sum", barmode = 'group', color = 'Search_Result_Exploration', text_auto=True)
fig6.show()

fig7 = px.histogram(df_exploded, x = ('age_group'), histfunc="sum", barmode = 'group', color = 'Search_Result_Exploration', text_auto=True)
fig7.show()

                                                      customer_id
category_split             Search_Result_Exploration
Beauty and Personal Care   First page                          78
                           Multiple pages                     240
Clothing and Fashion       First page                          93
                           Multiple pages                     250
Groceries and Gourmet Food First page                          21
                           Multiple pages                      90
Home and Kitchen           First page                          61
                           Multiple pages                     159
others                     First page                          50
                           Multiple pages                     116

In [ ]:
#Review reliability analysis by product category

cb_review_reliability = df_exploded.groupby(['Review_Reliability', 'Customer_Reviews_Importance']).agg({'customer_id':'nunique'})
display(cb_review_reliability)

fig7 = px.histogram (df_exploded, x='Review_Reliability', histfunc="sum", nbins=8, text_auto=True)
fig7.show()

fig8 = px.histogram(df_exploded, x = ('category_split'), histfunc="sum", barmode = 'group', color = 'Review_Reliability', text_auto=True)
fig8.show()

fig9 = px.histogram(df_exploded, x = ('age_group'), histfunc="sum", barmode = 'group', color = 'Review_Reliability', text_auto=True)
fig9.show()

                                                customer_id
Review_Reliability Customer_Reviews_Importance
Heavily            1                                    101
                   2                                     13
                   3                                     15
                   4                                     10
                   5                                     10
Moderately         1                                     47
                   2                                     51
                   3                                     78
                   4                                     17
                   5                                      6
Never              1                                      2
                   2                                      1
                   3                                      8
                   4                                      4
                   5                                      8
Occasionally       1                                     17
                   2                                     41
                   3                                     98
                   4                                     26
                   5                                      8
Rarely             1                                      2
                   2                                      9
                   3                                     17
                   4                                      7
                   5                                      6

In [ ]:
# relation between improvement areas and categories

fig10 = px.histogram(df_exploded, x = ('category_split'), histfunc="sum", barmode = 'group', color = 'Improvement_Areas_New', text_auto=True)
fig10.show()

In [ ]:
# Chi-square between improvement areas and categories

OD = pd.DataFrame()

import scipy.stats as stats

contingency_table = pd.crosstab(df_exploded['category_split'], df_exploded['Improvement_Areas_New'])

chi_res = stats.chi2_contingency(contingency_table)

print(f'p-value: {chi_res[1]}')

p-value: 0.020877713352807685

In [ ]:
df_exploded['Improvement_Areas_New'].unique()

array(['Reducing packaging waste', 'Product quality and accuracy',
       'Shipping speed and reliability',
       'Customer service responsiveness', 'Others'], dtype=object)

In [ ]:
df_exploded.groupby(['Improvement_Areas_New', 'category_split']).size().unstack(fill_value=0)

category_split,Beauty and Personal Care,Clothing and Fashion,Groceries and Gourmet Food,Home and Kitchen,others
Improvement_Areas_New,,,,,
Customer service responsiveness,121,127,45,76,50
Others,4,7,4,6,11
Product quality and accuracy,81,89,21,61,49
Reducing packaging waste,72,73,24,54,24
Shipping speed and reliability,40,47,17,23,32

In [ ]:
#Personalized_Recommendation_Frequency

cb_personalized_recommendation = df_exploded.groupby(['category_split', 'Personalized_Recommendation_Frequency']).agg({'customer_id':'nunique'})
display(cb_personalized_recommendation)

fig11 = px.histogram (df_exploded, x='Personalized_Recommendation_Frequency', histfunc="sum", nbins=8, text_auto=True)
fig11.show()

fig12 = px.histogram(df_exploded, x = ('category_split'), histfunc="sum", barmode = 'group', color = 'Personalized_Recommendation_Frequency', text_auto=True)
fig12.show()

fig13 = px.histogram(df_exploded, x = ('age_group'), histfunc="sum", barmode = 'group', color = 'Personalized_Recommendation_Frequency', text_auto=True)
fig13.show()

                                                                  customer_id
category_split             Personalized_Recommendation_Frequency
Beauty and Personal Care   No                                             121
                           Sometimes                                      118
                           Yes                                             79
Clothing and Fashion       No                                             146
                           Sometimes                                      127
                           Yes                                             70
Groceries and Gourmet Food No                                              38
                           Sometimes                                       37
                           Yes                                             36
Home and Kitchen           No                                             100
                           Sometimes                                       77
                           Yes                                             43
others                     No                                              80
                           Sometimes                                       53
                           Yes                                             33

In [ ]:
df_exploded.dtypes

## to drop: Timestamp, Customer_Reviews_Importance, Review_Helpfulness, Recommendation_Helpfulness, Shopping_Satisfaction, Service_Appreciation, 'Personalized_Recommendation_Frequency ' (with space)

Timestamp                                   object
age                                          int64
Gender                                      object
Purchase_Frequency                          object
Purchase_Categories                         object
Personalized_Recommendation_Frequency       object
Browsing_Frequency                          object
Product_Search_Method                       object
Search_Result_Exploration                   object
Customer_Reviews_Importance                  int64
Add_to_Cart_Browsing                        object
Cart_Completion_Frequency                   object
Cart_Abandonment_Factors                    object
Saveforlater_Frequency                      object
Review_Left                                 object
Review_Reliability                          object
Review_Helpfulness                          object
Personalized_Recommendation_Frequency        int64
Recommendation_Helpfulness                  object
Rating_Accuracy                              int64
Shopping_Satisfaction                        int64
Service_Appreciation                        object
Improvement_Areas                           object
customer_id                                 object
category_split                              object
age_group                                 category
Improvement_Areas_New                       object
dtype: object

In [ ]:
df_exploded.drop(columns=['Timestamp', 'Purchase_Frequency', 'Browsing_Frequency','Rating_Accuracy ','Saveforlater_Frequency','Customer_Reviews_Importance', 'Review_Helpfulness', 'Recommendation_Helpfulness', 'Shopping_Satisfaction', 'Service_Appreciation', 'Personalized_Recommendation_Frequency '])

,age,Gender,Purchase_Categories,Personalized_Recommendation_Frequency,Product_Search_Method,Search_Result_Exploration,Add_to_Cart_Browsing,Cart_Completion_Frequency,Cart_Abandonment_Factors,Review_Left,Review_Reliability,Improvement_Areas,customer_id,category_split,age_group,Improvement_Areas_New
0,23,Female,Beauty and Personal Care,Yes,Keyword,Multiple pages,Yes,Sometimes,Found a better price elsewhere,Yes,Occasionally,Reducing packaging waste,efe6a20e-278d-4256-9011-9c7c36785bde,Beauty and Personal Care,20-29,Reducing packaging waste
1,23,Female,Clothing and Fashion,Yes,Keyword,Multiple pages,Yes,Often,High shipping costs,No,Heavily,Reducing packaging waste,d6c5723a-6a01-4d35-99c4-08de25969e34,Clothing and Fashion,20-29,Reducing packaging waste
2,24,Prefer not to say,Groceries and Gourmet Food;Clothing and Fashion,No,Keyword,Multiple pages,Yes,Sometimes,Found a better price elsewhere,No,Occasionally,Product quality and accuracy,e876aa4a-c80a-4ea8-a473-8a40d294a056,Groceries and Gourmet Food,20-29,Product quality and accuracy
2,24,Prefer not to say,Groceries and Gourmet Food;Clothing and Fashion,No,Keyword,Multiple pages,Yes,Sometimes,Found a better price elsewhere,No,Occasionally,Product quality and accuracy,e876aa4a-c80a-4ea8-a473-8a40d294a056,Clothing and Fashion,20-29,Product quality and accuracy
3,24,Female,Beauty and Personal Care;Clothing and Fashion;...,Sometimes,Keyword,First page,Maybe,Sometimes,Found a better price elsewhere,Yes,Heavily,Product quality and accuracy,1d93ee7d-2c8b-45f6-80ae-dc364ffe157c,Beauty and Personal Care,20-29,Product quality and accuracy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599,23,Female,Beauty and Personal Care,Sometimes,categories,Multiple pages,Maybe,Sometimes,High shipping costs,Yes,Occasionally,Product quality and accuracy,da66537e-1375-4b0a-87d4-d6f67ead3cc0,Beauty and Personal Care,20-29,Product quality and accuracy
600,23,Female,Beauty and Personal Care;Clothing and Fashion;...,Yes,Keyword,Multiple pages,Yes,Often,others,No,Heavily,Product quality and accuracy,9f1a38a2-0b81-44cc-b715-de43cb83e079,Beauty and Personal Care,20-29,Product quality and accuracy
600,23,Female,Beauty and Personal Care;Clothing and Fashion;...,Yes,Keyword,Multiple pages,Yes,Often,others,No,Heavily,Product quality and accuracy,9f1a38a2-0b81-44cc-b715-de43cb83e079,Clothing and Fashion,20-29,Product quality and accuracy
600,23,Female,Beauty and Personal Care;Clothing and Fashion;...,Yes,Keyword,Multiple pages,Yes,Often,others,No,Heavily,Product quality and accuracy,9f1a38a2-0b81-44cc-b715-de43cb83e079,others,20-29,Product quality and accuracy
601,23,Female,Clothing and Fashion,Sometimes,Keyword,Multiple pages,Maybe,Often,Found a better price elsewhere,Yes,Moderately,Product quality and accuracy,570cf100-8825-4bde-84e1-9ba450eb7236,Clothing and Fashion,20-29,Product quality and accuracy

In [ ]:
cart_completion = df_exploded[['customer_id','Add_to_Cart_Browsing','Cart_Completion_Frequency','Cart_Abandonment_Factors']]
cart_completion

,customer_id,Add_to_Cart_Browsing,Cart_Completion_Frequency,Cart_Abandonment_Factors
0,efe6a20e-278d-4256-9011-9c7c36785bde,Yes,Sometimes,Found a better price elsewhere
1,d6c5723a-6a01-4d35-99c4-08de25969e34,Yes,Often,High shipping costs
2,e876aa4a-c80a-4ea8-a473-8a40d294a056,Yes,Sometimes,Found a better price elsewhere
2,e876aa4a-c80a-4ea8-a473-8a40d294a056,Yes,Sometimes,Found a better price elsewhere
3,1d93ee7d-2c8b-45f6-80ae-dc364ffe157c,Maybe,Sometimes,Found a better price elsewhere
...,...,...,...,...
599,da66537e-1375-4b0a-87d4-d6f67ead3cc0,Maybe,Sometimes,High shipping costs
600,9f1a38a2-0b81-44cc-b715-de43cb83e079,Yes,Often,others
600,9f1a38a2-0b81-44cc-b715-de43cb83e079,Yes,Often,others
600,9f1a38a2-0b81-44cc-b715-de43cb83e079,Yes,Often,others
601,570cf100-8825-4bde-84e1-9ba450eb7236,Maybe,Often,Found a better price elsewhere

In [ ]:
# replacing words with numbers

def update(x):
  return (x).replace('Yes','1').replace('Maybe','0.5').replace('No','0')

cart_completion['Add_to_Cart_Browsing'] = cart_completion['Add_to_Cart_Browsing'].apply(update)

def update2(x):
  return (x).replace('Always','1').replace('Often','0.75').replace('Sometimes','0.5').replace('Rarely','0.25').replace('Never','0')
cart_completion['Cart_Completion_Frequency'] = cart_completion['Cart_Completion_Frequency'].apply(update2)
#cart_completion[‘Completed Purchases’] = cart_completion[‘Add_to_Cart_Browsing’] * cart_completion[‘Cart_Completion_Frequency’]
#cart_completion[‘Abandoned Purchases’] = cart_completion[‘Add_to_Cart_Browsing’] - cart_completion[‘Completed Purchases’]
cart_completion.head(30)

<ipython-input-30-4a0262faee93>:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

<ipython-input-30-4a0262faee93>:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,customer_id,Add_to_Cart_Browsing,Cart_Completion_Frequency,Cart_Abandonment_Factors
0,efe6a20e-278d-4256-9011-9c7c36785bde,1,0.5,Found a better price elsewhere
1,d6c5723a-6a01-4d35-99c4-08de25969e34,1,0.75,High shipping costs
2,e876aa4a-c80a-4ea8-a473-8a40d294a056,1,0.5,Found a better price elsewhere
2,e876aa4a-c80a-4ea8-a473-8a40d294a056,1,0.5,Found a better price elsewhere
3,1d93ee7d-2c8b-45f6-80ae-dc364ffe157c,0.5,0.5,Found a better price elsewhere
3,1d93ee7d-2c8b-45f6-80ae-dc364ffe157c,0.5,0.5,Found a better price elsewhere
3,1d93ee7d-2c8b-45f6-80ae-dc364ffe157c,0.5,0.5,Found a better price elsewhere
4,a3bb243a-da88-4a0f-923e-4925f604a394,1,0.5,High shipping costs
4,a3bb243a-da88-4a0f-923e-4925f604a394,1,0.5,High shipping costs
5,3baf55a1-9197-4213-b62e-d9939e7820ea,1,0.25,Changed my mind or no longer need the item
6,85259524-a716-4d13-8e32-6bf87c276e81,1,0.75,High shipping costs
7,eeadd5b2-d22a-4ada-8d9b-66ec6475336d,1,0.75,Found a better price elsewhere
7,eeadd5b2-d22a-4ada-8d9b-66ec6475336d,1,0.75,Found a better price elsewhere
8,c04d803f-3d74-46cd-971c-ee8efb95d813,1,0.5,Changed my mind or no longer need the item
8,c04d803f-3d74-46cd-971c-ee8efb95d813,1,0.5,Changed my mind or no longer need the item
9,14041f66-a4c5-4a4f-b8a7-58fa79f8410d,1,0.25,Found a better price elsewhere
9,14041f66-a4c5-4a4f-b8a7-58fa79f8410d,1,0.25,Found a better price elsewhere
10,2725b77f-f463-4cce-87d3-fcf245b5dea7,0.5,0.5,Found a better price elsewhere
11,608db085-3a05-4b3c-b446-14a50554dfa8,1,0.5,High shipping costs
11,608db085-3a05-4b3c-b446-14a50554dfa8,1,0.5,High shipping costs
11,608db085-3a05-4b3c-b446-14a50554dfa8,1,0.5,High shipping costs
12,240699ac-69b8-4886-ad22-1eb87def2eb3,0.5,0.5,Changed my mind or no longer need the item
12,240699ac-69b8-4886-ad22-1eb87def2eb3,0.5,0.5,Changed my mind or no longer need the item
13,93cbfca3-27e7-43cc-9dad-419aba483b20,1,0.75,Changed my mind or no longer need the item
13,93cbfca3-27e7-43cc-9dad-419aba483b20,1,0.75,Changed my mind or no longer need the item
14,0b8001b2-9e8b-4ef7-af51-d301ee8757ed,1,0.75,Changed my mind or no longer need the item
15,8fee3710-6918-4461-aed9-46045e29d365,0.5,0.5,High shipping costs
16,1e3031b5-c107-45dc-b089-6980452fae95,1,0.5,Found a better price elsewhere
16,1e3031b5-c107-45dc-b089-6980452fae95,1,0.5,Found a better price elsewhere
17,c89c0f6a-587e-4abb-b46c-a069f894aba7,0.5,0.5,others

In [ ]:
# change to numeric values

cart_completion['Add_to_Cart_Browsing'] = pd.to_numeric(cart_completion['Add_to_Cart_Browsing'], errors='coerce')
cart_completion['Cart_Completion_Frequency'] = pd.to_numeric(cart_completion['Cart_Completion_Frequency'], errors='coerce')

<ipython-input-31-403866ede15d>:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

<ipython-input-31-403866ede15d>:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
#labeling columns
cart_completion['completed_purchases'] = cart_completion['Add_to_Cart_Browsing'] * cart_completion['Cart_Completion_Frequency']
cart_completion['abandoned_purchases'] = cart_completion['Add_to_Cart_Browsing'] - cart_completion['completed_purchases']
cart_completion.head(10)

<ipython-input-32-35df12f6140e>:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

<ipython-input-32-35df12f6140e>:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,customer_id,Add_to_Cart_Browsing,Cart_Completion_Frequency,Cart_Abandonment_Factors,completed_purchases,abandoned_purchases
0,efe6a20e-278d-4256-9011-9c7c36785bde,1.0,0.50,Found a better price elsewhere,0.50,0.50
1,d6c5723a-6a01-4d35-99c4-08de25969e34,1.0,0.75,High shipping costs,0.75,0.25
2,e876aa4a-c80a-4ea8-a473-8a40d294a056,1.0,0.50,Found a better price elsewhere,0.50,0.50
2,e876aa4a-c80a-4ea8-a473-8a40d294a056,1.0,0.50,Found a better price elsewhere,0.50,0.50
3,1d93ee7d-2c8b-45f6-80ae-dc364ffe157c,0.5,0.50,Found a better price elsewhere,0.25,0.25
3,1d93ee7d-2c8b-45f6-80ae-dc364ffe157c,0.5,0.50,Found a better price elsewhere,0.25,0.25
3,1d93ee7d-2c8b-45f6-80ae-dc364ffe157c,0.5,0.50,Found a better price elsewhere,0.25,0.25
4,a3bb243a-da88-4a0f-923e-4925f604a394,1.0,0.50,High shipping costs,0.50,0.50
4,a3bb243a-da88-4a0f-923e-4925f604a394,1.0,0.50,High shipping costs,0.50,0.50
5,3baf55a1-9197-4213-b62e-d9939e7820ea,1.0,0.25,Changed my mind or no longer need the item,0.25,0.75

In [ ]:
df_exploded_updated = pd.merge(df_exploded, cart_completion, on ='customer_id')

In [ ]:
amazon_clean= pd.read_csv('/content/amazon_table_clean (1).csv')

In [ ]:
df_exploded_updated.describe()

,age,Customer_Reviews_Importance,Personalized_Recommendation_Frequency,Rating_Accuracy,Shopping_Satisfaction,Add_to_Cart_Browsing_y,Cart_Completion_Frequency_y,completed_purchases,abandoned_purchases
count,3018.000000,3018.000000,3018.000000,3018.000000,3018.000000,3018.000000,3018.000000,3018.000000,3018.000000
mean,31.622929,2.268390,2.491716,2.508615,2.212061,0.583996,0.595842,0.367545,0.216451
std,9.820141,1.197529,1.108663,1.002528,1.059434,0.385973,0.224893,0.300408,0.191224
min,3.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,24.000000,1.000000,2.000000,2.000000,1.000000,0.500000,0.500000,0.125000,0.000000
50%,29.000000,2.000000,2.000000,2.000000,2.000000,0.500000,0.500000,0.250000,0.250000
75%,37.000000,3.000000,3.000000,3.000000,3.000000,1.000000,0.750000,0.500000,0.250000
max,67.000000,5.000000,5.000000,5.000000,5.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
df_exploded_grouped = df_exploded_updated.groupby(['category_split'], as_index=False).agg({'Customer_Reviews_Importance': 'mean', 'Rating_Accuracy ': 'mean', 'Shopping_Satisfaction': 'mean', 'Add_to_Cart_Browsing_y': 'mean', 'Cart_Completion_Frequency_y':'mean', 'completed_purchases':'mean', 'abandoned_purchases':'mean'})
df_exploded_grouped

,category_split,Customer_Reviews_Importance,Rating_Accuracy,Shopping_Satisfaction,Add_to_Cart_Browsing_y,Cart_Completion_Frequency_y,completed_purchases,abandoned_purchases
0,Beauty and Personal Care,2.247326,2.525401,2.220588,0.576203,0.595254,0.360127,0.216076
1,Clothing and Fashion,2.353808,2.512285,2.296069,0.564496,0.594287,0.355190,0.209306
2,Groceries and Gourmet Food,2.149051,2.327913,1.997290,0.574526,0.615854,0.372290,0.202236
3,Home and Kitchen,2.270736,2.536776,2.206573,0.579812,0.591941,0.366002,0.213811
4,others,2.243304,2.582589,2.229911,0.646205,0.588728,0.400670,0.245536

In [ ]:
df_exploded_updated.head(3)

,Timestamp,age,Gender,Purchase_Frequency,Purchase_Categories,Personalized_Recommendation_Frequency,Browsing_Frequency,Product_Search_Method,Search_Result_Exploration,Customer_Reviews_Importance,...,Improvement_Areas,customer_id,category_split,age_group,Improvement_Areas_New,Add_to_Cart_Browsing_y,Cart_Completion_Frequency_y,Cart_Abandonment_Factors_y,completed_purchases,abandoned_purchases
0,2023/06/04 1:28:19 PM GMT+5:30,23,Female,Few times a month,Beauty and Personal Care,Yes,Few times a week,Keyword,Multiple pages,1,...,Reducing packaging waste,efe6a20e-278d-4256-9011-9c7c36785bde,Beauty and Personal Care,20-29,Reducing packaging waste,1.0,0.50,Found a better price elsewhere,0.50,0.50
1,2023/06/04 2:30:44 PM GMT+5:30,23,Female,Once a month,Clothing and Fashion,Yes,Few times a month,Keyword,Multiple pages,1,...,Reducing packaging waste,d6c5723a-6a01-4d35-99c4-08de25969e34,Clothing and Fashion,20-29,Reducing packaging waste,1.0,0.75,High shipping costs,0.75,0.25
2,2023/06/04 5:04:56 PM GMT+5:30,24,Prefer not to say,Few times a month,Groceries and Gourmet Food;Clothing and Fashion,No,Few times a month,Keyword,Multiple pages,2,...,Product quality and accuracy,e876aa4a-c80a-4ea8-a473-8a40d294a056,Groceries and Gourmet Food,20-29,Product quality and accuracy,1.0,0.50,Found a better price elsewhere,0.50,0.50

In [ ]:
import pandas as pd

amazon_merged = pd.merge(amazon_clean, df_exploded_updated, right_on='category_split', left_on='general_category', how='left')

In [ ]:
amazon_merged